apiVersion: v1
kind: Pod
metadata:
  name: dotnet-app
  labels:
    app: dotnet-app
spec:
  containers:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:7.0-alpine
    command:
    - /bin/sh
    - -c
    - 'sleep infinity'
  - name: publish
    image: mcr.microsoft.com/dotnet/aspnet:7.0-alpine
    command:
    - /bin/sh
    - -c
    - 'sleep infinity'
